ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('',include('userapp.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/userapp/urls.py
from django.urls import path,include
from . import views

app_name='userss'

urlpatterns = [
    path('',views.basePage,name='base-page' ),
    path('login/',views.log_in,name='login-url' ),
    path('logout/',views.log_out,name='logout-url' ),
    path('signup/',views.Signup,name='signup-url' ),

    path('c_prod_list/',views.customerProdList,name='customer-prod-list-url'),
    path('c_prod_list/jackets/',views.jacketsPage,name='jackets-url'),
    path('c_prod_list/shirts/',views.shirtsPage,name='shirts-url'),
    path('c_prod_list/tshirts/',views.tshirtsPage,name='tshirts-url'),
    path('c_prod_list/jeans/',views.jeansPage,name='jeans-url'),
    path('c_prod_list/shorts/',views.shortsPage,name='shorts-url'),
    path('c_prod_list/tights/',views.tightsPage,name='tights-url'),
    path('c_prod_list/trousers/',views.trousersPage,name='trousers-url'),
    path('c_prod_list/joggers/',views.joggersPage,name='joggers-url'),
    path('c_prod_list/sneakers/',views.sneakersPage,name='sneakers-url'),
    path('c_prod_list/pumps/',views.pumpsPage,name='pumps-url'),
    path('c_prod_list/heels/',views.heelsPage,name='heels-url'),

    path('c_prod_list/women/',views.womenPage,name='women-url'),
    path('c_prod_list/women/jackets/',views.womenJacketsPage,name='women-jackets-url'),
    path('c_prod_list/women/shirts/',views.womenShirtsPage,name='women-shirts-url'),
    path('c_prod_list/women/tshirts/',views.womenTshirtsPage,name='women-tshirts-url'),
    path('c_prod_list/women/jeans/',views.womenJeansPage,name='women-jeans-url'),
    path('c_prod_list/women/shorts/',views.womenShortsPage,name='women-shorts-url'),
    path('c_prod_list/women/tights/',views.womenTightsPage,name='women-tights-url'),
    path('c_prod_list/women/trousers/',views.womenTrousersPage,name='women-trousers-url'),
    path('c_prod_list/women/joggers/',views.womenJoggersPage,name='women-joggers-url'),
    path('c_prod_list/women/sneakers/',views.womenSneakersPage,name='women-sneakers-url'),
    path('c_prod_list/women/pumps/',views.womenPumpsPage,name='women-pumps-url'),
    path('c_prod_list/women/heels/',views.womenHeelsPage,name='women-heels-url'),

    path('c_prod_list/men/',views.menPage,name='men-url'),
    path('c_prod_list/men/jackets/',views.menJacketsPage,name='men-jackets-url'),
    path('c_prod_list/men/shirts/',views.menShirtsPage,name='men-shirts-url'),
    path('c_prod_list/men/tshirts/',views.menTshirtsPage,name='men-tshirts-url'),
    path('c_prod_list/men/jeans/',views.menJeansPage,name='men-jeans-url'),
    path('c_prod_list/men/shorts/',views.menShortsPage,name='men-shorts-url'),
    path('c_prod_list/men/tights/',views.menTightsPage,name='men-tights-url'),
    path('c_prod_list/men/trousers/',views.menTrousersPage,name='men-trousers-url'),
    path('c_prod_list/men/joggers/',views.menJoggersPage,name='men-joggers-url'),
    path('c_prod_list/men/sneakers/',views.menSneakersPage,name='men-sneakers-url'),
    path('c_prod_list/men/pumps/',views.menPumpsPage,name='men-pumps-url'),
    path('c_prod_list/men/heels/',views.menHeelsPage,name='men-heels-url'),

    path('c_prod_list/kids/',views.kidsPage,name='kids-url'),
    path('c_prod_list/kids/jackets/',views.kidsJacketsPage,name='kids-jackets-url'),
    path('c_prod_list/kids/shirts/',views.kidsShirtsPage,name='kids-shirts-url'),
    path('c_prod_list/kids/tshirts/',views.kidsTshirtsPage,name='kids-tshirts-url'),
    path('c_prod_list/kids/jeans/',views.kidsJeansPage,name='kids-jeans-url'),
    path('c_prod_list/kids/shorts/',views.kidsShortsPage,name='kids-shorts-url'),
    path('c_prod_list/kids/tights/',views.kidsTightsPage,name='kids-tights-url'),
    path('c_prod_list/kids/trousers/',views.kidsTrousersPage,name='kids-trousers-url'),
    path('c_prod_list/kids/joggers/',views.kidsJoggersPage,name='kids-joggers-url'),
    path('c_prod_list/kids/sneakers/',views.kidsSneakersPage,name='kids-sneakers-url'),
    path('c_prod_list/kids/pumps/',views.kidsPumpsPage,name='kids-pumps-url'),
    path('c_prod_list/kids/heels/',views.kidsHeelsPage,name='kids-heels-url'),

    path('vendor_home/',views.vendorHome,name='vendor-home-url' ),
    path('v_prod_list/',views.vendorProdList,name='vendor-prod-list-url'),
    path('v_prod_add/',views.vendorProdAdd,name='vendor-prod-add-url'),
    path('v_prod_list/v_update/<int:id>/',views.vendorProdUpdate,name='vendor-prod-update-url'),
    path('v_prod_list/v_delete/<int:id>/',views.vendorProdDelete,name='vendor-prod-delete-url'),
    path('v_orders/',views.vendorOrders,name='vendor-all-orders-url'),
    path('v_orders_by_customer/',views.vendorOrdersByCustomer,name='vendor-orders-by-customer-url'),

    path('cart/',views.cartView,name='cart-url'),
    path('checkout/',views.checkoutView,name='checkout-url'),
    path('pay/',views.payView,name='pay-url'),

    path('update_order/',views.updateOrderView,name='update-order-url'),

]

ecommerce/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
{%load static%}
  <head>
    <meta charset="utf-8">
    <title></title>
    <script type="text/javascript">
    function getCookie(name) {
      let cookieValue = null;
      if (document.cookie && document.cookie !== '') {
          const cookies = document.cookie.split(';');
          for (let i = 0; i < cookies.length; i++) {
              const cookie = cookies[i].trim();
              // Does this cookie string begin with the name we want?
              if (cookie.substring(0, name.length + 1) === (name + '=')) {
                  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                  break;
              }
          }
      }
      return cookieValue;
    }
    const csrftoken = getCookie('csrftoken');
    </script>
    <link rel="stylesheet" href="{%static 'ecommerce/css/cpl.css'%}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </head>
  <body style="background-color:#e3e8e7">

  {%if user.is_authenticated%}
    <ul class="mynav">
      {%block homenav%}
      <li class="li"> <a class="mylink" href="#"> Home</a></li>
      {%endblock%}
      <li class="li"> <a class="mylink" href="#"> About</a></li>
      <li class="li"> <a class="mylink" href="#"> Contact</a></li>
      <li class="li-right"> <a class="logout" href="{%url 'userss:logout-url'%}">Logout, {{request.user|capfirst}}</a></li>
    </ul>
  {%endif%}

    {%block content%}
    <p> <a href="{% url 'userss:login-url' %}" >Login</a> </p>

    <p> <a href="{% url 'userss:signup-url' %}" >Signup</a> </p>
    {%endblock%}

  </body>
  <script type="text/javascript" src="{%static 'ecommerce/js/cart.js'%}"></script>
</html>