ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('',include('userapp.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/userapp/urls.py
from django.urls import path,include
from . import views

app_name='userss'

urlpatterns = [
    path('',views.basePage,name='base-page' ),
    path('login/',views.log_in,name='login-url' ),
    path('logout/',views.log_out,name='logout-url' ),
    path('signup/',views.Signup,name='signup-url' ),

    path('c_prod_list/',views.customerProdList,name='customer-prod-list-url'),
    path('c_prod_list/jackets/',views.jacketsPage,name='jackets-url'),
    path('c_prod_list/shirts/',views.shirtsPage,name='shirts-url'),
    path('c_prod_list/tshirts/',views.tshirtsPage,name='tshirts-url'),
    path('c_prod_list/jeans/',views.jeansPage,name='jeans-url'),
    path('c_prod_list/shorts/',views.shortsPage,name='shorts-url'),
    path('c_prod_list/tights/',views.tightsPage,name='tights-url'),
    path('c_prod_list/trousers/',views.trousersPage,name='trousers-url'),
    path('c_prod_list/joggers/',views.joggersPage,name='joggers-url'),
    path('c_prod_list/sneakers/',views.sneakersPage,name='sneakers-url'),
    path('c_prod_list/pumps/',views.pumpsPage,name='pumps-url'),
    path('c_prod_list/heels/',views.heelsPage,name='heels-url'),

    path('c_prod_list/women/',views.womenPage,name='women-url'),
    path('c_prod_list/women/jackets/',views.womenJacketsPage,name='women-jackets-url'),
    path('c_prod_list/women/shirts/',views.womenShirtsPage,name='women-shirts-url'),
    path('c_prod_list/women/tshirts/',views.womenTshirtsPage,name='women-tshirts-url'),
    path('c_prod_list/women/jeans/',views.womenJeansPage,name='women-jeans-url'),
    path('c_prod_list/women/shorts/',views.womenShortsPage,name='women-shorts-url'),
    path('c_prod_list/women/tights/',views.womenTightsPage,name='women-tights-url'),
    path('c_prod_list/women/trousers/',views.womenTrousersPage,name='women-trousers-url'),
    path('c_prod_list/women/joggers/',views.womenJoggersPage,name='women-joggers-url'),
    path('c_prod_list/women/sneakers/',views.womenSneakersPage,name='women-sneakers-url'),
    path('c_prod_list/women/pumps/',views.womenPumpsPage,name='women-pumps-url'),
    path('c_prod_list/women/heels/',views.womenHeelsPage,name='women-heels-url'),

    path('c_prod_list/men/',views.menPage,name='men-url'),
    path('c_prod_list/men/jackets/',views.menJacketsPage,name='men-jackets-url'),
    path('c_prod_list/men/shirts/',views.menShirtsPage,name='men-shirts-url'),
    path('c_prod_list/men/tshirts/',views.menTshirtsPage,name='men-tshirts-url'),
    path('c_prod_list/men/jeans/',views.menJeansPage,name='men-jeans-url'),
    path('c_prod_list/men/shorts/',views.menShortsPage,name='men-shorts-url'),
    path('c_prod_list/men/tights/',views.menTightsPage,name='men-tights-url'),
    path('c_prod_list/men/trousers/',views.menTrousersPage,name='men-trousers-url'),
    path('c_prod_list/men/joggers/',views.menJoggersPage,name='men-joggers-url'),
    path('c_prod_list/men/sneakers/',views.menSneakersPage,name='men-sneakers-url'),
    path('c_prod_list/men/pumps/',views.menPumpsPage,name='men-pumps-url'),
    path('c_prod_list/men/heels/',views.menHeelsPage,name='men-heels-url'),

    path('c_prod_list/kids/',views.kidsPage,name='kids-url'),
    path('c_prod_list/kids/jackets/',views.kidsJacketsPage,name='kids-jackets-url'),
    path('c_prod_list/kids/shirts/',views.kidsShirtsPage,name='kids-shirts-url'),
    path('c_prod_list/kids/tshirts/',views.kidsTshirtsPage,name='kids-tshirts-url'),
    path('c_prod_list/kids/jeans/',views.kidsJeansPage,name='kids-jeans-url'),
    path('c_prod_list/kids/shorts/',views.kidsShortsPage,name='kids-shorts-url'),
    path('c_prod_list/kids/tights/',views.kidsTightsPage,name='kids-tights-url'),
    path('c_prod_list/kids/trousers/',views.kidsTrousersPage,name='kids-trousers-url'),
    path('c_prod_list/kids/joggers/',views.kidsJoggersPage,name='kids-joggers-url'),
    path('c_prod_list/kids/sneakers/',views.kidsSneakersPage,name='kids-sneakers-url'),
    path('c_prod_list/kids/pumps/',views.kidsPumpsPage,name='kids-pumps-url'),
    path('c_prod_list/kids/heels/',views.kidsHeelsPage,name='kids-heels-url'),

    path('vendor_home/',views.vendorHome,name='vendor-home-url' ),
    path('v_prod_list/',views.vendorProdList,name='vendor-prod-list-url'),
    path('v_prod_add/',views.vendorProdAdd,name='vendor-prod-add-url'),
    path('v_prod_list/v_update/<int:id>/',views.vendorProdUpdate,name='vendor-prod-update-url'),
    path('v_prod_list/v_delete/<int:id>/',views.vendorProdDelete,name='vendor-prod-delete-url'),
    path('v_orders/',views.vendorOrders,name='vendor-all-orders-url'),
    path('v_orders_by_customer/',views.vendorOrdersByCustomer,name='vendor-orders-by-customer-url'),

    path('cart/',views.cartView,name='cart-url'),
    path('checkout/',views.checkoutView,name='checkout-url'),
    path('pay/',views.payView,name='pay-url'),

    path('update_order/',views.updateOrderView,name='update-order-url'),

]

ecommerce/userapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from .models import MyUser,Product,Order
from django.contrib.auth import authenticate
from django.contrib.auth.models import User

class CustomerForm1(UserCreationForm):
    class Meta:
        model=User
        fields=['username','password1','password2']
        widgets={
                    'username':forms.TextInput(attrs={'placeholder':'Username..'}),
                    'password1':forms.TextInput(attrs={'placeholder':'Password..'}),
                    'password2':forms.TextInput(attrs={'placeholder':'Confirm Password..'}),
                }

class CustomerForm2(forms.ModelForm):
    class Meta:
        model=MyUser
        fields=('firstname','lastname','email','Register_As')
        widgets={
                    'firstname':forms.TextInput(attrs={'placeholder':'Firstname..'}),
                    'email':forms.EmailInput(attrs={'placeholder':'Email..'}),
                    'lastname':forms.TextInput(attrs={'placeholder':'Lastname..'}),
                }

class AddProductForm(forms.ModelForm):
    class Meta:
        model=Product
        fields=['seller','title','description','price','stock','img','type']
        widgets={
                    'seller':forms.HiddenInput(),
                    'title':forms.TextInput(attrs={'placeholder':'Title..','class':'title'}),
                    'description':forms.Textarea(attrs={'placeholder':'Description..','class':'description'}),
                    'price':forms.NumberInput(attrs={'placeholder':'Price..','class':'price'}),
                    'stock':forms.NumberInput(attrs={'placeholder':'Quantity..','class':'stock'}),
                }

ecommerce/userapp/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.urls import reverse,reverse_lazy
from . import forms
from . import models
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login,logout
from django.http import JsonResponse
import json
# Create your views here.
def vendorHome(request):
    return render(request,'userapp/vendorhome.html')
def vendorProdList(request):
    current_user=request.user
    my_user=models.MyUser.objects.get(user=current_user.id)
    prod=models.Product.objects.filter(seller=my_user)
    return render(request,'userapp/vendorprodlist.html',{'prodt':prod})
def vendorProdAdd(request):
    form=forms.AddProductForm()
    if request.method=='POST':
        form=forms.AddProductForm(request.POST,request.FILES)
        if form.is_valid():
            current_user=request.user
            my_user=models.MyUser.objects.get(user=current_user.id)
            prod=form.save(commit=False)
            prod.seller=my_user
            prod.save()
            return redirect('userss:vendor-prod-list-url')
    else:
        form=forms.AddProductForm()
    return render(request,'userapp/vendorprodadd.html',{'form':form})
def vendorProdUpdate(request,id):
    prod=get_object_or_404(models.Product,id=id)
    if request.method=='POST':
        form=forms.AddProductForm(request.POST,instance=prod)
        if form.is_valid():
            current_user=request.user
            my_user=models.MyUser.objects.get(user=current_user.id)
            prod=form.save(commit=False)
            prod.seller=my_user
            prod.save()
            return redirect('userss:vendor-prod-list-url')
    else:
        form=forms.AddProductForm(instance=prod)
    return render(request,'userapp/vendorprodupdate.html',{'form':form})
def vendorProdDelete(request,id):
    prod=get_object_or_404(models.Product,id=id)
    if request.method=='POST':
        prod.delete()
        return redirect('userss:vendor-prod-list-url')
    return render(request,'userapp/vendorproddelete.html',{'prod':prod})
def vendorOrders(request):
    current_user=request.user.myuser
    prod=models.Product.objects.filter(seller=current_user)
    order=models.Order.objects.all()
    item=models.Item.objects.filter(product__in=prod)

    print(prod)
    print(order)
    print(item)
    print()

    return render(request,'userapp/vendororders.html',{'order':order,'item':item})
def vendorOrdersByCustomer(request):

    return render(request,'userapp/ordersbycustomer.html',{})
def basePage(request):
    return render(request,'base.html')
def Signup(request):
    form1=forms.CustomerForm1()
    form2=forms.CustomerForm2()
    if request.method=='POST':
        form1=forms.CustomerForm1(request.POST)
        form2=forms.CustomerForm2(request.POST)
        if form1.is_valid() and form2.is_valid():
            user1=form1.save()
            user2=form2.save(commit=False)
            user2.user=user1
            user2.save()
            messages.success(request,'Account Created!')
            return redirect('userss:login-url')
    else:
        form1=forms.CustomerForm1()
        form2=forms.CustomerForm2()
    context={'form1':form1,'form2':form2}
    return render(request,'userapp/signup.html',context)
def log_in(request):
    if request.method=='POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            user=form.get_user()
            login(request,user)
            my_user=models.MyUser.objects.get(user_id=user.id)
            if my_user.Register_As=='S':
                return redirect('userss:vendor-home-url')
            elif my_user.Register_As=='B':
                return redirect('userss:customer-prod-list-url')
    else:
        form=AuthenticationForm()
    return render(request,'userapp/login.html',{'form':form})
def log_out(request):
    logout(request)
    return redirect('userss:login-url')

def customerProdList(request):
    prod=models.Product.objects.all()
    return render(request,'userapp/customerprodlist.html',{'prod':prod})
def jacketsPage(request):
    prod=models.Product.objects.filter(type='Jackets')
    return render(request,'userapp/customerprodlist.html',{'prod':prod})
def shirtsPage(request):
    prod=models.Product.objects.filter(type='Shirts')
    return render(request,'userapp/customerprodlist.html',{'prod':prod})
def tshirtsPage(request):
    prod=models.Product.objects.filter(type='T-shirts')
    return render(request,'userapp/customerprodlist.html',{'prod':prod})
def jeansPage(request):
    prod=models.Product.objects.filter(type='Jeans')
    return render(request,'userapp/customerprodlist.html',{'prod':prod})
def shortsPage(request):
    prod=models.Product.objects.filter(type='Shorts')
    return render(request,'userapp/customerprodlist.html',{'prod':prod})
def tightsPage(request):
    prod=models.Product.objects.filter(type='Tights')
    return render(request,'userapp/customerprodlist.html',{'prod':prod})
def trousersPage(request):
    prod=models.Product.objects.filter(type='Trousers')
    return render(request,'userapp/customerprodlist.html',{'prod':prod})
def joggersPage(request):
    prod=models.Product.objects.filter(type='Joggers')
    return render(request,'userapp/customerprodlist.html',{'prod':prod})
def sneakersPage(request):
    prod=models.Product.objects.filter(type='Sneakers')
    return render(request,'userapp/customerprodlist.html',{'prod':prod})
def pumpsPage(request):
    prod=models.Product.objects.filter(type='Pumps')
    return render(request,'userapp/customerprodlist.html',{'prod':prod})
def heelsPage(request):
    prod=models.Product.objects.filter(type='Heels')
    return render(request,'userapp/customerprodlist.html',{'prod':prod})

def womenPage(request):
    prod=models.Product.objects.filter(category='W')
    return render(request,'userapp/womenlist.html',{'prod':prod})
def womenJacketsPage(request):
    prod=models.Product.objects.filter(type='Jackets').filter(category='W')
    return render(request,'userapp/womenlist.html',{'prod':prod})
def womenShirtsPage(request):
    prod=models.Product.objects.filter(type='Shirts').filter(category='W')
    return render(request,'userapp/womenlist.html',{'prod':prod})
def womenTshirtsPage(request):
    prod=models.Product.objects.filter(type='T-shirts').filter(category='W')
    return render(request,'userapp/womenlist.html',{'prod':prod})
def womenJeansPage(request):
    prod=models.Product.objects.filter(type='Jeans').filter(category='W')
    return render(request,'userapp/womenlist.html',{'prod':prod})
def womenShortsPage(request):
    prod=models.Product.objects.filter(type='Shorts').filter(category='W')
    return render(request,'userapp/womenlist.html',{'prod':prod})
def womenTightsPage(request):
    prod=models.Product.objects.filter(type='Tights').filter(category='W')
    return render(request,'userapp/womenlist.html',{'prod':prod})
def womenTrousersPage(request):
    prod=models.Product.objects.filter(type='Trousers').filter(category='W')
    return render(request,'userapp/womenlist.html',{'prod':prod})
def womenJoggersPage(request):
    prod=models.Product.objects.filter(type='Joggers').filter(category='W')
    return render(request,'userapp/womenlist.html',{'prod':prod})
def womenSneakersPage(request):
    prod=models.Product.objects.filter(type='Sneakers').filter(category='W')
    return render(request,'userapp/womenlist.html',{'prod':prod})
def womenPumpsPage(request):
    prod=models.Product.objects.filter(type='Pumps').filter(category='W')
    return render(request,'userapp/womenlist.html',{'prod':prod})
def womenHeelsPage(request):
    prod=models.Product.objects.filter(type='Heels').filter(category='W')
    return render(request,'userapp/womenlist.html',{'prod':prod})

def menPage(request):
    prod=models.Product.objects.filter(category='M')
    return render(request,'userapp/menlist.html',{'prod':prod})
def menJacketsPage(request):
    prod=models.Product.objects.filter(type='Jackets').filter(category='M')
    return render(request,'userapp/menlist.html',{'prod':prod})
def menShirtsPage(request):
    prod=models.Product.objects.filter(type='Shirts').filter(category='M')
    return render(request,'userapp/menlist.html',{'prod':prod})
def menTshirtsPage(request):
    prod=models.Product.objects.filter(type='T-shirts').filter(category='M')
    return render(request,'userapp/menlist.html',{'prod':prod})
def menJeansPage(request):
    prod=models.Product.objects.filter(type='Jeans').filter(category='M')
    return render(request,'userapp/menlist.html',{'prod':prod})
def menShortsPage(request):
    prod=models.Product.objects.filter(type='Shorts').filter(category='M')
    return render(request,'userapp/menlist.html',{'prod':prod})
def menTightsPage(request):
    prod=models.Product.objects.filter(type='Tights').filter(category='M')
    return render(request,'userapp/menlist.html',{'prod':prod})
def menTrousersPage(request):
    prod=models.Product.objects.filter(type='Trousers').filter(category='M')
    return render(request,'userapp/menlist.html',{'prod':prod})
def menJoggersPage(request):
    prod=models.Product.objects.filter(type='Joggers').filter(category='M')
    return render(request,'userapp/menlist.html',{'prod':prod})
def menSneakersPage(request):
    prod=models.Product.objects.filter(type='Sneakers').filter(category='M')
    return render(request,'userapp/menlist.html',{'prod':prod})
def menPumpsPage(request):
    prod=models.Product.objects.filter(type='Pumps').filter(category='M')
    return render(request,'userapp/menlist.html',{'prod':prod})
def menHeelsPage(request):
    prod=models.Product.objects.filter(type='Heels').filter(category='M')
    return render(request,'userapp/menlist.html',{'prod':prod})

def kidsPage(request):
    prod=models.Product.objects.filter(category='K')
    return render(request,'userapp/kidslist.html',{'prod':prod})
def kidsJacketsPage(request):

ecommerce/userapp/templates/userapp/customerprodlist.html
{%extends 'base.html'%}

{%block homenav%}
<li class="li"> <a class="mylink" href="{%url 'userss:customer-prod-list-url'%}"> Home</a></li>
{%endblock%}

{%block content%}
  <style>
  .card {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    max-width: 300px;
    margin: auto;
    text-align: center;
    font-family: arial;
  }

  .price {
    color: grey;
    font-size: 22px;
  }

  .card button {
    border: none;
    outline: 0;
    padding: 12px;
    color: white;
    background-color: #000;
    text-align: center;
    cursor: pointer;
    width: 100%;
    font-size: 18px;
  }

  .card button:hover {
    opacity: 0.7;
  }
  .dropdown {
    position: relative;
    display: inline-block;
  }

  .dropdown-content {

    display: none;
    position: absolute;
    background-color: #f1f1f1;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
  }

  .dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
  }

  .dropdown-content a:hover {background-color: #ddd;}

  .dropdown:hover .dropdown-content {display: block;}

  .dropdown:hover .dropbtn {background-color: ;
    cursor: pointer;
  }
</style>
  <ul style="background-color:#0f122b;" class="mynav">
    <li class="li"> <a class="mylink" href="{%url 'userss:women-url'%}">Women</a> </li>
    <li class="li"> <a class="mylink" href="{%url 'userss:men-url'%}">Men</a> </li>
    <li class="li"> <a class="mylink" href="{%url 'userss:kids-url'%}">Kids</a> </li>

  </ul>
  <div class="navbar navbar-fixed-top" >
    <div class="row">
      <div class="col-md-4">
        <div class="dropdown">
          <a class="dropbtn">Upper Wear</a>
          <div class="dropdown-content">
            <a style="" href="{%url 'userss:jackets-url'%}">Jackets</a>
            <a href="{%url 'userss:shirts-url'%}">Shirts</a>
            <a href="{%url 'userss:tshirts-url'%}">Tshirts</a>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="dropdown">
          <a class="dropbtn">Bottom Wear</a>
          <div class="dropdown-content">
            <a href="{%url 'userss:jeans-url'%}">Jeans</a>
            <a href="{%url 'userss:shorts-url'%}">Shorts</a>
            <a href="{%url 'userss:tights-url'%}">Tights</a>
            <a href="{%url 'userss:trousers-url'%}">Trousers</a>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="dropdown">
          <a class="dropbtn">Shoes</a>
          <div class="dropdown-content">
            <a href="{%url 'userss:joggers-url'%}">Joggers</a>
            <a href="{%url 'userss:sneakers-url'%}">Sneakers</a>
            <a href="{%url 'userss:pumps-url'%}">Pumps</a>
            <a href="{%url 'userss:heels-url'%}">Heels</a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="">
    <a href="{%url 'userss:cart-url'%}" type="button" name="button">View Cart</a>
  </div>

  <div class="row">
    {%for product in prod%}
    <div class="col-md-4">

      <div class="card" style="width: 18rem;">
        <img src="{{product.img.url}}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{product.title}}</h5>
          <p class="card-text">{{product.description}}</p>
          <p>Rem. Stock: {{product.stock}}</p>
          {% if product.stock > 0 %}
          <a data-product={{product.id}} data-action="add" href="#" class="btn btn-primary update-cart">
            <i class="bi bi-cart4"></i> Add To Cart
          </a>
          {%elif product.stock <= 0 %}
            More stock will be added soon!
          {%endif%}
        </div>
      </div>
    </div>
    {%endfor%}

  </div>
  {%endblock%}

ecommerce/userapp/templates/userapp/kidslist.html
{%extends 'base.html'%}

{%block homenav%}
<li class="li"> <a class="mylink" href="{%url 'userss:customer-prod-list-url'%}"> Home</a></li>
{%endblock%}

{%block content%}
  <style>
  .card {
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    max-width: 300px;
    margin: auto;
    text-align: center;
    font-family: arial;
  }

  .price {
    color: grey;
    font-size: 22px;
  }

  .card button {
    border: none;
    outline: 0;
    padding: 12px;
    color: white;
    background-color: #000;
    text-align: center;
    cursor: pointer;
    width: 100%;
    font-size: 18px;
  }

  .card button:hover {
    opacity: 0.7;
  }
  .dropdown {
    position: relative;
    display: inline-block;
  }

  .dropdown-content {
    display: none;
    position: absolute;
    background-color: #f1f1f1;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
  }

  .dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
  }

  .dropdown-content a:hover {background-color: #ddd;}

  .dropdown:hover .dropdown-content {display: block;}

  .dropdown:hover .dropbtn {background-color: ;
    cursor: pointer;
  }
</style>
<ul style="background-color:#0f122b;" class="mynav">
  <li class="li"> <a class="mylink" href="{%url 'userss:women-url'%}">Women</a> </li>
  <li class="li"> <a class="mylink" href="{%url 'userss:men-url'%}">Men</a> </li>
  <li class="li"> <a class="mylink" href="#">Kids</a> </li>

</ul>
  <div class="container">

    <div class="row">
      <div class="col-md-4">
        <div class="dropdown">
          <a class="dropbtn">Upper Wear</a>
          <div class="dropdown-content">
            <a href="{%url 'userss:kids-jackets-url'%}">Jackets</a>
            <a href="{%url 'userss:kids-shirts-url'%}">Shirts</a>
            <a href="{%url 'userss:kids-tshirts-url'%}">Tshirts</a>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="dropdown">
          <a class="dropbtn">Bottom Wear</a>
          <div class="dropdown-content">
            <a href="{%url 'userss:kids-jeans-url'%}">Jeans</a>
            <a href="{%url 'userss:kids-shorts-url'%}">Shorts</a>
            <a href="{%url 'userss:kids-tights-url'%}">Tights</a>
            <a href="{%url 'userss:kids-trousers-url'%}">Trousers</a>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="dropdown">
          <a class="dropbtn">Shoes</a>
          <div class="dropdown-content">
            <a href="{%url 'userss:kids-joggers-url'%}">Joggers</a>
            <a href="{%url 'userss:kids-sneakers-url'%}">Sneakers</a>
            <a href="{%url 'userss:kids-pumps-url'%}">Pumps</a>
            <a href="{%url 'userss:kids-heels-url'%}">Heels</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="">
    <a href="{%url 'userss:cart-url'%}" type="button" name="button">View Cart</a>
  </div>
  <div class="row">

    {%for product in prod%}
    <div class="col-md-4">

      <div class="card" style="width: 18rem;">
        <img src="{{product.img.url}}" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{product.title}}</h5>
          <p class="card-text">{{product.description}}</p>
          <p>Rem. Stock: {{product.stock}}</p>
          {% if product.stock > 0 %}
          <a data-product={{product.id}} data-action="add" href="#" class="btn btn-primary update-cart">
            <i class="bi bi-cart4"></i> Add To Cart
          </a>
          {%elif product.stock <= 0 %}
            More stock will be added soon!
          {%endif%}
        </div>
      </div>
    </div>
    {%endfor%}

  </div>
  {%endblock%}

ecommerce/userapp/templates/userapp/ordersbycustomer.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    asdasd
  </body>
</html>

ecommerce/userapp/templates/userapp/vendorhome.html
{%extends 'base.html'%}

{%block content%}
<br><br>
  <a class="vh" href="{%url 'userss:vendor-prod-list-url'%}">View/Update/Delete/Add Product</a> <br>
  <a class="vh" href="{%url 'userss:vendor-all-orders-url'%}">View all Orders</a> <br>
  <a href="{%url 'userss:vendor-orders-by-customer-url'%}"></a> <br>
{%endblock%}

ecommerce/userapp/templates/userapp/vendorprodlist.html
{%extends 'base.html'%}
{%block homenav%}
<li class="li"> <a class="mylink" href="{%url 'userss:vendor-home-url'%}"> Home</a></li>
{%endblock%}
{%block content%}
  {%if prodt%}
    <h2 class="vplh"> &nbsp&nbsp  List of All the Products of {{request.user|capfirst}}</h2><hr class="line">
    <table  class="vplt">
        <tr class="vplthr">
          <th><b>Title</b></th>
          <th><b>Description</b></th>
          <th><b>Price</b></td>
          <th><b>Quantity</b></th>
          <th><b>Image</b></th>
          <th><b></b></th>
          <th><b></b></th>
        </tr>
        {%for item in prodt%}
        <tr class="vpltr">
          <td>  {{item.title}}</td>
          <td>  {{item.description}}</td>
          <td>  {{item.price}}</td>
          <td>  {{item.stock}}</td>
          <td> <a href="../media/{{item.img}}"> <img height="70px"src="{{item.img.url}}"> </a> </td>
          <td> <a class="btn btn-primary" href="{%url 'userss:vendor-prod-update-url' item.id%}"> Update </a> </td>
          <td> <a class="btn btn-warning" href="{%url 'userss:vendor-prod-delete-url' item.id%}"> Delete </a> </td>
        </tr>
        {%endfor%}
    </table>
  {%else%}
    <h5>No Products Added Yet!</h5>
  {%endif%}
  <a style="margin-left:10%; margin-top:1%;" class="btn btn-dark" href="{%url 'userss:vendor-prod-add-url'%}"> Add a Product </a>
{%endblock%}